---
name: Chart-OFC2
version: 0.03_03
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: Generate html and data files for use with Open Flash Chart version 2
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp::Clan: 0
  JSON::XS: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
build_requires:
  File::Slurp: 0
  Test::Differences: 0
  Test::More: 0
provides:
  Chart::OFC2:
    file: lib/Chart/OFC2.pm
    version: 0.03_03
  Chart::OFC2::Area::Hollow:
    file: lib/Chart/OFC2/Line.pm
    version: 0.01
  Chart::OFC2::Axis:
    file: lib/Chart/OFC2/Axis.pm
    version: 0.01
  Chart::OFC2::Bar:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::3D:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::Fade:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::Filled:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::Glass:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::Sketch:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::Bar::Stack:
    file: lib/Chart/OFC2/Bar.pm
    version: 0.01
  Chart::OFC2::BarLineBase:
    file: lib/Chart/OFC2/BarLineBase.pm
    version: 0.01
  Chart::OFC2::Element:
    file: lib/Chart/OFC2/Element.pm
    version: 0.01
  Chart::OFC2::Extremes:
    file: lib/Chart/OFC2/Extremes.pm
    version: 0.01
  Chart::OFC2::HBar:
    file: lib/Chart/OFC2/HBar.pm
    version: 0.01
  Chart::OFC2::HBarValues:
    file: lib/Chart/OFC2/HBarValues.pm
    version: 0.01
  Chart::OFC2::Labels:
    file: lib/Chart/OFC2/Labels.pm
    version: 0.01
  Chart::OFC2::Line:
    file: lib/Chart/OFC2/Line.pm
    version: 0.01
  Chart::OFC2::Line::Dot:
    file: lib/Chart/OFC2/Line.pm
    version: 0.01
  Chart::OFC2::Line::Hollow:
    file: lib/Chart/OFC2/Line.pm
    version: 0.01
  Chart::OFC2::Pie:
    file: lib/Chart/OFC2/Pie.pm
    version: 0.01
  Chart::OFC2::PieValues:
    file: lib/Chart/OFC2/PieValues.pm
    version: 0.01
  Chart::OFC2::Scatter:
    file: lib/Chart/OFC2/Scatter.pm
    version: 0.01
  Chart::OFC2::Title:
    file: lib/Chart/OFC2/Title.pm
    version: 0.01
  Chart::OFC2::ToolTip:
    file: lib/Chart/OFC2/ToolTip.pm
    version: 0.01
  Chart::OFC2::XAxis:
    file: lib/Chart/OFC2/Axis.pm
  Chart::OFC2::YAxis:
    file: lib/Chart/OFC2/Axis.pm
  Chart::OFC2::YAxisRight:
    file: lib/Chart/OFC2/Axis.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
